"""enforce non-null status and is_starter

Revision ID: 3d275688d880
Revises: b4f0540e8b9d
Create Date: 2026-05-25 13:38:02.645116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d275688d880'
down_revision: Union[str, None] = 'b4f0540e8b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
