"""add unique constraints to rosters and lineups

Revision ID: b4f0540e8b9d
Revises: 192c278a7e4a
Create Date: 2026-05-25 13:26:23.731979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4f0540e8b9d'
down_revision: Union[str, None] = '192c278a7e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lineups', 'is_starter',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint('uq_lineup_user_player', 'lineups', ['user_id', 'player_id'])
    op.alter_column('players', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uq_roster_user_player', 'rosters', ['user_id', 'player_id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_roster_user_player', 'rosters', type_='unique')
    op.alter_column('players', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_lineup_user_player', 'lineups', type_='unique')
    op.alter_column('lineups', 'is_starter',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
